# 服务端口
server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9000/eureka/
    register-with-eureka: true
    # 示此客户端是否应从 eureka 服务器获取 eureka 注册表信息。
    fetch-registry: true
#  instance:
#    prefer-ip-address: true

spring:
  # 数据源
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
      pool-name: hikai-pool
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: myorder


# mybatis SQL 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-group1
    send-message-timeout: 30000
# 下面的配置主要是主动pull模式，参见：https://github.com/apache/rocketmq-spring/wiki/%E6%8E%A5%E6%94%B6%E6%B6%88%E6%81%AF
#  consumer:
#    group: my-consumer-group
#    topic: myOrderTopic
#    listeners:

# properties used in the application
my:
  rocketmq:
    topicUser: user-topic
    topic: mytopic
    orderTopic: myOrderTopic
    msgExtTopic: myMsgExtTopic
    transTopic: myTransTopic
    bytesRequestTopic: bytesRequestTopic:tagA
    stringRequestTopic: stringRequestTopic:tagA
    objectRequestTopic: objectRequestTopic:tagA
    genericRequestTopic: genericRequestTopic:tagA
    extNameServer: 127.0.0.1:9876


#  # default producer tls config
#  rocketmq.producer.tls-enable=false
#  # self ext producer tls config
#  demo.rocketmq.ext.useTLS=false

# tx-manager 配置
tx-lcn:
  client:
    #    manager-address: 192.168.1.102:8070
    manager-address: 127.0.0.1:8070
logging:
  level:
    com:
      codingapi: debug
